### ISSUE TITLE
Transfer repository and gem ownership

### ISSUE THREAD

**Issue by Songmu** [mackerelio/fluent-plugin-mackerel#10]
Thank you for creating and maintaining great gem.
We Mackerel development team want to maintain this gem with you.

So, could you try following steps?

## Add gem ownership to me

    % gem owner fluent-plugin-mackerel -a 'y.songmu@gmail.com'

## Transfer repositroy to mackerelio organizaion

You can transfer repository from setting tab right hand, but you might not transfer repository directly to mackerelio organization because of permission level.
If so, could you transfer the repo to me(Songmu)?

Thanks for your cooperation!

**Comment by tksmd** [comment]
@Songmu First, I've done adding ownership of this gem to you. See below.
- https://rubygems.org/gems/fluent-plugin-mackerel

I'll try transfering ownership soon later. Thanks!

**Comment by tksmd** [comment]
I just tried transfering ownership but it's rejected with the error like this

** Songmu/fluent-plugin-mackerel already exists **

You have already forked version of the repository, so could you rename yours first ? Then I'll try again.

**Comment by Songmu** [comment]
Oops. I removed forked repository.

**Comment by tksmd** [comment]
Thanks! I'm now sending request to transfer ownership.

**Comment by Songmu** [comment]
https://github.com/mackerelio/fluent-plugin-mackerel

Done! Thanks.

I'll rewrite copyright later.

**Comment by tksmd** [comment]
> I'll rewrite copyright later.

I see, Thanks for all of your help so far and I believe many users can trust this plugin as your team officially supports it :smile: :smile: :smile:

**Comment by Songmu** [comment]
@tksmd I invited you to collaborators team. Accept it. Thanks!
